config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :symptoms
  end

  root 'welcome#index'

  resources :drugs do 
    collection do
      post 'search'
      get 'result', to: 'drugs#show'
      get 'profile'
    end
  end

end

app/models/drug.rb
class Drug < ActiveRecord::Base

	def self.main(search_query, hits)
		all = Object.new
		puts hits
		auth = {:username => "USER", :password => "KEY"}
		count, response = search_idapi(search_query,0, hits)
		if count > 0
			 results = response['drugResultsOutput']['SearchResults']['Drug']
		else
			puts 'no match'
		end
		# print the results
		return count, results
	end

	# query the Gene Variants API
	def self.search_idapi(query, offset, hits)
		auth = {:username => "Hackathon_07", :password => "MT79CL3S54RXZH2B"}
		end_point = "https://lsapi-demo.thomson-pharma.com/ls-api-ws/ws/rs/drugs-v1/drug"
		puts "#{end_point}/search?query=#{query}&offset=#{offset}&hits=#{hits}"
		response = HTTParty.get("#{end_point}/search?query=#{query}&offset=#{offset}&hits=#{hits}", :digest_auth => auth)
		puts "#{response} is my response"
		count = response['drugResultsOutput']['totalResults'].to_i
		return count, response
	end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :symptoms, dependent: :destroy 
  accepts_nested_attributes_for :symptoms  

end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  belongs_to :patient
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/:name
  # GET /drugs/:name.json
  def show
    @response = Drug.main(params[:name], params[:count])
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /drugs/search
  def search
    redirect_to result_drugs_path(:count => params[:quantity],:name =>params[:name])
  end

  def profile
    puts params
    @drug_profile = Drug.main("drugId:" + params[:name], 1)
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:name, :name_key, :company, :phase, :last_modified, :change_date, :added_date)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    3.times { @patient.symptoms.build }
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :address, :city, :state, :zip, symptoms_attributes:[:id, :name, :_destroy])
    end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController

  def new
    @symptom = Symptom.new
  end

  def edit
  end

  def create
    @symptom = Symptom.new(symp_params)
    respond to do |format|
      if @symptom.save
        format.html {redirect_to patients_url(params[:patient_id]) }
      else
        format.html { render :new }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond to do |format|
      if @symptom.update(symp_params)
        format.html {redirect_to patients_url(params[:patient_id]) }
      else
        format.html { render :new }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @symptom.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Symptom Removed' }
    end
  end

  private

  def set_symptom
    @symptom = @symptom.find(params[:id])
  end

  def symp_params
    param.require(:symptom).permit(:name, :patient_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drugs/_form.html.erb
<%= form_for(@drug) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_key %><br>
    <%= f.text_field :name_key %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :phase %><br>
    <%= f.text_field :phase %>
  </div>
  <div class="field">
    <%= f.label :last_modified %><br>
    <%= f.datetime_select :last_modified %>
  </div>
  <div class="field">
    <%= f.label :change_date %><br>
    <%= f.datetime_select :change_date %>
  </div>
  <div class="field">
    <%= f.label :added_date %><br>
    <%= f.datetime_select :added_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug, class: 'btn btn-info' %>
<%= link_to 'Back', drugs_path, class: 'btn btn-warning' %>

app/views/drugs/index.html.erb
<h1>Listing drugs</h1>

<%= form_tag search_drugs_path do |f| %>
<div class="form-group form-section-left">
  <%= label_tag 'name' %>
  <%= text_field_tag 'name', nil, class:'form-control', placeholder:'Enter Name of Drug' %>
</div>

<div class="form-group form-section-right">
  <%= label_tag 'quantity' %>
  <%= number_field_tag 'quantity', nil, class:'form-control', placeholder: 50 %>
</div>

<div class="form-group">
  <%= submit_tag 'Search', class:'btn btn-success', id: 'drugSearch' %>
  <%= link_to 'Home', root_path, class: 'btn btn-info' %>
</div>

<% end %> 

app/views/drugs/new.html.erb
<h1>New drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/profile.html.erb
<% drug = @drug_profile[1] %>
<div class="row-fluid equal">
  <div class="col-md-12">
    <h3 class="text-center">Now Showing: <%= drug["name"] %>
      <span class="label label-info">Highest Phase: <%= drug["phaseHighest"] %></span>
    </h3>
  </div>
</div>

<hr>

<div class="row-fluild equal">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Summary</h3>
      </div>
      <div class="panel-body">
        <%= raw(drug["Summary"]) %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">Companies</div>
      </div>
      <div class="panel-body">
        <ul>
          <li><strong>Origin:</strong> <%= drug["CompanyOriginator"] %></li>
          <li><%= drug["CompaniesPrimary"]["Company"] %></li>
        </ul>
      </div>
    </div>
  </div>

</div>

<div class="row-fluid equal">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Primary Indicators</h3>
      </div>
      <div class="panel-body">
        <% if drug["IndicationsPrimary"]["Indication"].nil? %>
          <%= drug["IndicationsPrimary"]["Indication"] %>  
        <% else %>
          <p>No Values Found</p>
        <% end %>      
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Primary Actions</h3>
      </div>
      <div class="panel-body">
        <% if !drug["ActionsPrimary"].nil? %>
          <%= drug["ActionsPrimary"]["Action"] %>
        <% else %>
          <p>No Values Found</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Technologies</h3>
      </div>
      <div class="panel-body">
        <% if drug["Technologies"]["Technology"].size > 1 %>
          <%= drug["Technologies"]["Technology"] %>
        <% else %>
          <ul>
          <% drug["Technologies"]["Technology"].each do |tech| %>
              <li><%= tech %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row-fluid equal">
  <div class="col-md-12">
    <%= link_to 'Home', drugs_path, class: 'btn btn-info' %>
  </div>
</div>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Results</h1>

<div class="result-list">
<% if @response.length > 0 %>
<% @response.each do |item| %>
  <% if item.is_a?(Array) %>

  <table id="drugTable" class="table table-inverse table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Clinical Phase</th>
        <th>Company</th>
        <th>Technology</th>
      </tr>
    </thead>

    <tbody>
      <% item.each do |sub_item| %>
        <tr>
          <th><%= link_to "#{sub_item['name']}", profile_drugs_path(:name => sub_item["id"]) %></th>
          <th><%= sub_item["phaseHighest"] %></th>
          <th><%= sub_item["CompanyOriginator"] %></th>
          <% if sub_item["Technologies"]["Technology"].is_a?(Array) %>
           <th>
          <% sub_item["Technologies"]["Technology"].each do |tech| %>
          <%= tech %>,
          <% end %>
          </th>
          <% else %>
          <th><%= sub_item["Technologies"]["Technology"] %></th>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <% if item.is_a?(Hash) %>
      <div class="result-data">
        <table id="drugTable" class="table table-inverse table-bordered" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Clinical Phase</th>
              <th>Company</th>
              <th>Technology</th>
            </tr>
          </thead>

          <tbody>
              <tr>
                <th><%= link_to "#{item['name']}", profile_drugs_path(:name => item["id"]) %></th>
                <th><%= item["phaseHighest"] %></th>
                <th><%= item["CompanyOriginator"] %></th>
                <% if item["Technologies"]["Technology"].is_a?(Array) %>
                 <th>
                <% item["Technologies"]["Technology"].each do |tech| %>
                <%= tech %>,
                <% end %>
                </th>
                <% else %>
                <th><%= item["Technologies"]["Technology"] %></th>
                <% end %>
              </tr>
          </tbody>
        </table>
    </div>
    <% end %>
  <% end %>
<% end %>
<% else %>
There were no matches. Please press the back link below and do a search again.
<% end %>
</div>
<%= link_to 'Back', drugs_path, class: 'btn btn-primary' %>
<%= link_to 'Home', root_path, class: 'btn btn-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Selector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.css">
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="http://cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.js"></script>
</head>
<body id="master">

  <%= render 'shared/navbar' %>

  <div class="container" id="main">
    <%= yield %>
  </div>

  <%= render 'shared/footer' %>

</body>

</html>

app/views/patients/_form.html.erb
<%= nested_form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</p>
      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-section-left">
    <div class="form-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-section-right">
    <div class="form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :state %><br>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :zip %><br>
      <%= f.text_field :zip, class: 'form-control' %>
    </div>
  </div>

  <% f.fields_for :symptoms do |builder| %>
    <div class="form-group">
      <%= builder.label :name, "Symptom Name" %>
      <%= builder.text_field :name, class: 'form-control symptom-control' %>
      <br>
      <%= builder.link_to_remove "Remove this Symptom", class: 'btn btn-warning' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.link_to_add "Add Symptom", :symptoms, class: 'btn btn-default' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Credentials for <%= @patient.first_name %> <%= @patient.last_name %></h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @patient, class: 'btn btn-primary' %>
<%= link_to 'Back', patients_path, class: 'btn btn-default' %>
<%= link_to 'Home', root_path, class: 'btn btn-info' %>

app/views/patients/index.html.erb
<h1>My Patients</h1>

<div class="well">
  <table id="patientTable" class="table table-hover" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.first_name %></td>
          <td><%= patient.last_name %></td>
          <td><%= patient.address %></td>
          <td><%= patient.city %></td>
          <td><%= patient.state %></td>
          <td><%= patient.zip %></td>
          <td><%= link_to 'Show', patient ,class: 'label label-success' %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient), class: 'label label-primary'%></td>
          <td><%= link_to 'Delete', patient, class: 'label label-warning', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-primary' %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path, class: 'btn btn-primary' %>

app/views/patients/show.html.erb
<h1>Patient Data</h1>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @patient.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @patient.zip %>
</p>

<p>Symptoms</p>
<ul>
<% multiple = false %>
<% query_str = "" %>
<% @patient.symptoms.each do |s| %>
  <li>
    <%= s.name %>
    <% if !multiple %>
     <% query_str = "indicationsPrimary:" + s.name.gsub(/\s/,'%20') %>
     <% multiple = true %>
    <% else %>
    <% query_str = query_str + "%20AND%20indicationsPrimary:%20" + s.name.gsub(/\s/, '%20') %>
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to 'Generate', result_drugs_path(:name => query_str, :count => 500), class: 'btn btn-primary' %> 
<%= link_to 'Edit', edit_patient_path(@patient), class: 'btn btn-default' %>
<%= link_to 'Back', patients_path, class: 'btn btn-success' %>
<%= link_to 'Home', root_path, class: 'btn btn-info' %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <p class="text-muted">Powered by the <a href="http://hackathontr.azurewebsites.net/?page_id=141">Thomson Reuters Cortellis API</a>. Built by <a href="https://github.com/tenji240">Tenji Tembo</a> and <a href="https://github.com/danich1">David Nicholson</a> <em class="pull-right">Demo Application</em></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Selector</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li rel="tooltip" data-toggle="tooltip" data-placement="bottom" title="Drugs" ><a href="/drugs"><i class="fa fa-plus" ></i></a></li>
        <li><a href="/patients"><i class="fa fa-building-o"></i></a></li>
        <li><a href="/"><i class="fa fa-home"></i></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/welcome/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="inner cover">
      <h1 class="text-center">Welcome to Selector</h1>
      <p>Selector is a Pharmecutial Drug Research and Suggestion Tool designed to bring in the new age of personal medicine. Using the Thomson Reuters
        Cortellis API and Database, we provide an interface that empowers physicians to make informed decisions about their patients, as well as stay up to date with important information regarding pharmecuticals.</p>
      <p class="text-center"><%= link_to "Research Pharmecuticals", drugs_path, class: 'btn btn-primary' %> <%= link_to "View My Patients", patients_path, class: 'btn btn-default' %></p>
    </div>
  </div>
</div>